# Site settings
title: philgrayphilgray
email: philgrayphilgray@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Phil Gray is a writer, musician, and digital content developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://philgrayphilgray.com" # the base hostname & protocol for your site
paginate: 1
paginate_path: "/page:num/"
twitter_username:
github_username:
bandcamp_username: http://floraflora.bandcamp.com/
linkedin_url: http://www.linkedin.com/in/philgrayphilgray


# Build settings
# Warning: Adding highlighter will cause page build failure on github pages.
markdown: kramdown
highlighter: pygments